{% set name = "rocm-cmake" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RadeonOpenCompute/rocm-cmake/archive/roc-{{ version }}.tar.gz
  sha256: a394b3209533b38e18d7d8ce357d4fdc5c9fc1ef3a82140d558fa38621702921

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
  run:

test:
  commands:
    - test -f $PREFIX/share/rocm/cmake/ROCMConfig.cmake

about:
  home: https://github.com/RadeonOpenCompute/rocm-cmake
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Rocm cmake modules

extra:
  recipe-maintainers:
    - isuruf
