{% set name = "rocm-cmake" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/rocm-cmake/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: 8b37d458e801b486521f12d18ca2103125173dd0f1130d37c8c36e795d34772b

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
  run:

test:
  commands:
    - test -f $PREFIX/share/rocm/cmake/ROCMConfig.cmake

about:
  home: https://github.com/ROCm/rocm-cmake
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Rocm cmake modules'

extra:
  recipe-maintainers:
    - isuruf
