{% set name = "rocm-cmake" %}
{% set version = "6.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/rocm-cmake/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: 76bfac6fba31a9c4ec196d9b9b2d5ec51b8b68840b3fba8686aa42323d76a425

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
  run:

test:
  commands:
    - test -f $PREFIX/share/rocm/cmake/ROCMConfig.cmake

about:
  home: https://github.com/ROCm/rocm-cmake
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Rocm cmake modules'

extra:
  recipe-maintainers:
    - isuruf
